"""
สคริปต์สร้าง secrets.toml อัตโนมัติจากไฟล์ JSON
ใช้งาน: python setup_secrets.py
"""

import json
import os

print("🔐 สคริปต์สร้าง secrets.toml อัตโนมัติ")
print("=" * 50)

# ค้นหาไฟล์ JSON ในโฟลเดอร์ปัจจุบัน
json_files = [f for f in os.listdir('.') if f.endswith('.json')]

if not json_files:
    print("\n❌ ไม่พบไฟล์ JSON ในโฟลเดอร์นี้!")
    print("💡 กรุณาวางไฟล์ JSON ที่ดาวน์โหลดจาก Google Cloud ไว้ในโฟลเดอร์โปรเจกต์")
    print("   แล้วรันสคริปต์นี้ใหม่อีกครั้ง")
    input("\nกด Enter เพื่อออก...")
    exit(1)

print(f"\n✅ พบไฟล์ JSON: {len(json_files)} ไฟล์")
for i, f in enumerate(json_files, 1):
    print(f"   {i}. {f}")

# ถ้ามีหลายไฟล์ ให้เลือก
if len(json_files) > 1:
    print("\n📌 กรุณาเลือกไฟล์ที่ต้องการ:")
    choice = input(f"ใส่หลข (1-{len(json_files)}): ").strip()
    try:
        json_file = json_files[int(choice) - 1]
    except:
        print("❌ เลือกไม่ถูกต้อง!")
        input("กด Enter เพื่อออก...")
        exit(1)
else:
    json_file = json_files[0]

print(f"\n📂 ใช้ไฟล์: {json_file}")

# อ่านไฟล์ JSON
try:
    with open(json_file, 'r', encoding='utf-8') as f:
        creds = json.load(f)
    print("✅ อ่านไฟล์ JSON สำเร็จ")
except Exception as e:
    print(f"❌ อ่านไฟล์ JSON ไม่สำเร็จ: {e}")
    input("กด Enter เพื่อออก...")
    exit(1)

# ถามชื่อ Google Sheet
print("\n📊 ชื่อ Google Sheet ที่คุณสร้างไว้?")
print("   (ตัวอย่าง: Thrift Shop Inventory)")
sheet_name = input("ชื่อ Sheet: ").strip()

if not sheet_name:
    print("⚠️ ไม่ได้ใส่ชื่อ ใช้ชื่อเริ่มต้น: Thrift Shop Inventory")
    sheet_name = "Thrift Shop Inventory"

# สร้างโฟลเดอร์ .streamlit ถ้ายังไม่มี
if not os.path.exists('.streamlit'):
    os.makedirs('.streamlit')
    print("✅ สร้างโฟลเดอร์ .streamlit แล้ว")

# สร้างเนื้อหา secrets.toml
secrets_content = f'''# Auto-generated by setup_secrets.py
# อย่าแชร์ไฟล์นี้กับใคร!

sheet_name = "{sheet_name}"

[gcp_service_account]
type = "{creds.get('type', '')}"
project_id = "{creds.get('project_id', '')}"
private_key_id = "{creds.get('private_key_id', '')}"
private_key = """{creds.get('private_key', '')}"""
client_email = "{creds.get('client_email', '')}"
client_id = "{creds.get('client_id', '')}"
auth_uri = "{creds.get('auth_uri', '')}"
token_uri = "{creds.get('token_uri', '')}"
auth_provider_x509_cert_url = "{creds.get('auth_provider_x509_cert_url', '')}"
client_x509_cert_url = "{creds.get('client_x509_cert_url', '')}"
universe_domain = "{creds.get('universe_domain', 'googleapis.com')}"
'''

# บันทึกไฟล์
secrets_path = os.path.join('.streamlit', 'secrets.toml')
try:
    with open(secrets_path, 'w', encoding='utf-8') as f:
        f.write(secrets_content)
    print(f"\n✅ สร้างไฟล์ {secrets_path} สำเร็จ!")
except Exception as e:
    print(f"❌ บันทึกไฟล์ไม่สำเร็จ: {e}")
    input("กด Enter เพื่อออก...")
    exit(1)

# แสดงข้อมูลสำคัญ
print("\n" + "=" * 50)
print("📋 สรุปข้อมูล:")
print(f"   Sheet Name: {sheet_name}")
print(f"   Project ID: {creds.get('project_id', 'N/A')}")
print(f"   Client Email: {creds.get('client_email', 'N/A')}")
print("=" * 50)

print("\n⚠️ สิ่งที่ต้องทำต่อ:")
print("1. เปิด Google Sheet ของคุณ")
print("2. คลิกปุ่ม 'Share' (มุมขวาบน)")
print(f"3. วางอีเมลนี้: {creds.get('client_email', '')}")
print("4. เลือก 'Editor' (ต้องเป็น Editor!)")
print("5. ยกเลิกติ๊ก 'Notify people'")
print("6. คลิก 'Share'")
print("\n✅ เสร็จแล้วรันคำสั่ง: streamlit run app.py")

print("\n" + "=" * 50)
print("🎉 ตั้งค่าเสร็จสมบูรณ์!")
input("\nกด Enter เพื่อออก...")
